---
- name: Install etcd
  apt:
    update_cache: yes
    state: present
    pkg:
      - etcd

- name: Configure etcd
  template:
    src: "roles/install-etcd/templates/etcd.j2"
    dest: /etc/default/etcd

- name: Start service etcd
  systemd:
    name: etcd
    state: restarted
    enabled: yes
