---
- name: Install postgres
  apt:
    update_cache: yes
    state: present
    pkg:
      - postgresql
      - python
      - python3-pip
      - libpq-dev

- name: stop postgres
  service:
    name: postgresql
    state: stopped

- name: Create a symbolic link
  file:
    src: /var/lib/postgresql/12/bin/*
    dest: /usr/sbin/*
    owner: root
    group: root
    state: link
    force: yes

- name: Upgrade setuptools
  pip:
    name: setuptools
    state: latest

- name: Install packages(pip)
  pip:
    state: latest
    name:
      - psycopg2
      - psycopg2-binary
      - patroni
      - python-consul
      - python-etcd

- name: Configure patroni.yml
  template:
    src: "roles/install-postgres/templates/patroni.yml.j2"
    dest: /etc/patroni.yml

- name: Create /data/patroni
  file:
    path: /data/patroni
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Configure patroni.service
  copy:
    src: "roles/install-postgres/files/patroni.service"
    dest: /etc/systemd/system/

- name: Start services
  systemd:
    daemon_reload: yes
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - patroni
    - postgresql
